# This configuration tells Starship to display nothing at all
format = ""
add_newline = false

[
character
]
disabled = true

# Explicitly disable all other modules
[
directory
]
disabled = true
[
package
]
disabled = true
[
python
]
disabled = true
[
nodejs
]
disabled = true
[
git_branch
]
disabled = true
[
git_status
]
disabled = true
[
docker_context
]
disabled = true
[
aws
]
disabled = true
[
gcloud
]
disabled = true
[
kubernetes
]
disabled = true
# ... add any other modules you use in your main configuration